- name: Configure /etc/hosts on all nodes
  hosts: all
  become: yes
  roles:
    - configure_hosts

- name: Install elasticsearch on all nodes
  hosts: all
  become: yes
  roles:
    - install_elasticsearch

- name: Configure Elasticsearch Cluster
  hosts: all
  become: yes
  roles:
    - configure_elasticsearch
