# - name: Configure /etc/hosts on all nodes
#   hosts: all
#   become: yes
#   roles:
#     - configure_hosts

# - hosts: all
#   gather_facts: false
#   tasks:
#     - name: Debug connection
#       ansible.builtin.ping:

- name: Install elasticsearch on all nodes
  hosts: all
  become: yes
  roles:
    - install_elasticsearch

- name: Configure Elasticsearch Cluster
  hosts: all
  become: yes
  roles:
    - configure_elasticsearch

- name: Install and configure Kibana
  hosts: node-2
  become: yes
  roles:
    - install_kibana
    - configure_kibana